coarse_config:
  params:
    block_config:
    - 6
    - 12
    - 12
    bn_size: 4
    dropout_prob: 0.0
    feature_l: 256
    growth_rate: 32
    in_channels: 1
    init_features: 64
    loss_fn: WingLoss
    lr: 0.00010752040143064647
    n_landmarks: 4
    project_gt: false
  type: SADenseNet
feature_freeze_patience: null
loss_weights:
- 0.7417713992978388
- 0.8534516444221382
lr: 0.001
optimizer: AdamW
refinement_config:
  params:
    coord_embedding_l: 64
    dropout: 0.06929242297160013
    leg_embedding_l: 128
    loss_fn: WingLoss
    lr: 6.113980231447991e-06
    mlp_dim: 512
    n_landmarks: 4
    n_legs: 2
    num_heads: 2
    num_layers: 2
    patch_feature_l: 64
    patch_size: 16
    poi_embedding_l: 64
    poi_feature_l: 256
    project_gt: false
    warmup_epochs: -1
  type: PatchTransformer
scheduler_config:
  params:
    end_factor: 0.1
    start_factor: 1
    total_iters: 38
  type: LinearLR
